version: "3.7"

networks:
  tfgrid_bknd:
    name: tfgrid_bknd
    ipam:
      driver: default
      config:
        - subnet: "172.28.0.0/24"

services:
  tfchain-public-node:
    ports:
      - "9944:9944"
      - "9933:9933"
      - "9615:9615"
      - "30333:30333"
    volumes:
      - /srv/tfchain/:/storage/
    image: threefolddev/tfchain:2.2.0-rc8
    restart: unless-stopped
    networks:
      - tfgrid_bknd
    command:
      - "--node-key"
      - "baad0200d185d1ec4434b197f78a1bcb74aa9d8ee9c591c55390ea910b505f8b"
      - "--base-path"
      - "/storage"
      - "--chain"
      - "/etc/chainspecs/dev/chainSpecRaw.json"
      - "--port"
      - "30333"
      - "--bootnodes"
      - "/ip4/185.206.122.7/tcp/30333/ws/p2p/12D3KooWRdfuKqX8hULMZz521gdqZB2TXJjfrJE5FV71WiuAUrpk"
      - "--rpc-cors"
      - "all"
      - "--prometheus-external"
      - "--ws-external"
      - "--ws-max-connections=148576"
      - "--pruning"
      - "archive"
      - "--telemetry-url"
      - "wss://shard1.telemetry.tfchain.grid.tf/submit 1"
      - "--rpc-methods=Safe"
      - "--rpc-external"
