version: "3.7"

networks:
  tfgrid_bknd:
    name: tfgrid_bknd
    ipam:
      driver: default
      config:
        - subnet: "172.28.0.0/24"

services:
  tfchain-public-node:
    container_name: tfchain-main-public-node
    ports:
      - "9944:9944"
      - "9933:9933"
      - "9615:9615"
      - "30333:30333"
    volumes:
      - /srv/tfchain/:/storage/
    image: threefolddev/tfchain:2.2.0-rc8
    restart: unless-stopped
    networks:
      tfgrid_bknd:
        ipv4_address: 172.28.0.2
    command:
      - "--node-key"
      - "baad0200d185d1ec4434b197f78a1bcb74aa9d8ee9c591c55390ea910b505f8b"
      - "--base-path"
      - "/storage"
      - "--chain"
      - "/etc/chainspecs/dev/chainSpecRaw.json"
      - "--port"
      - "30333"
      - "--bootnodes"
      - "/ip4/185.206.122.7/tcp/30333/ws/p2p/12D3KooWRdfuKqX8hULMZz521gdqZB2TXJjfrJE5FV71WiuAUrpk"
      - "--rpc-cors"
      - "all"
      - "--prometheus-external"
      - "--ws-external"
      - "--ws-max-connections=148576"
      - "--pruning"
      - "archive"
      - "--telemetry-url"
      - "wss://shard1.telemetry.tfchain.grid.tf/submit 1"
      - "--rpc-methods=Safe"
      - "--rpc-external"

  db:
    depends_on:
      - tfchain-public-node
    image: cockroachdb/cockroach:v22.2.2
    restart: unless-stopped
    networks:
      tfgrid_bknd:
        ipv4_address: 172.28.0.3
    ports:
      - "26257:26257"
      - "8080:8080"
    command: start-single-node --insecure
    volumes:
      - /srv/indexer/:/cockroach/cockroach-data

  ingest:
    depends_on:
      - tfchain-public-node
      - db
    restart: unless-stopped
    networks:
      tfgrid_bknd:
        ipv4_address: 172.28.0.4
    image: subsquid/substrate-ingest:1
    volumes:
      - "./typesBundle.json:/configs/typesBundle.json"
    command:
      [
        "-e",
        "${WS_ENDPOINT}",
        "-c",
        "20",
        "--out",
        "postgres://root@db:26257/defaultdb",
        "--types-bundle",
        "/configs/typesBundle.json"
      ]

  gateway:
    depends_on:
      - tfchain-public-node
      - db
    image: subsquid/substrate-gateway:2.5.0
    restart: unless-stopped
    networks:
      tfgrid_bknd:
        ipv4_address: 172.28.0.5
    environment:
      DATABASE_MAX_CONNECTIONS: 5
      RUST_LOG: "actix_web=info,actix_server=info"
    command: [ "--database-url", "postgres://root@db:26257/defaultdb" ]
    ports:
      - "8888:8000"

  explorer:
    depends_on:
      - tfchain-public-node
    image: subsquid/substrate-explorer:firesquid
    restart: unless-stopped
    networks:
      tfgrid_bknd:
        ipv4_address: 172.28.0.6
    environment:
      DB_TYPE: cockroach
      DB_HOST: db
      DB_PORT: "26257"
      DB_NAME: "defaultdb"
      DB_USER: "root"
    ports:
      - "4444:3000"

#  grid-activation-service:
#    container_name: grid_activation-service
#    image: ghcr.io/threefoldtech/tfchain_activation_service:1.0.2
#    restart: unless-stopped
#    networks:
#      tfgrid_bknd:
#        ipv4_address: 172.28.0.7
#    environment:
#      - URL=wss://tfchain.dev.grid.tf
#      - MNEMONIC=news mad appear brave weekend first eyebrow blouse mask hedgehog toilet exhaust
#      - KYC_PUBLIC_KEY=somekey
#      - ACTIVATION_AMOUNT=1000000

  grid-dashboard:
    container_name: grid_dashboard
    image: threefolddev/tfgrid_dashboard:v1.3.0-rc1
    restart: unless-stopped
    networks:
      tfgrid_bknd:
        ipv4_address: 172.28.0.8
    environment:
      - GQL_URL=https://graphql.dev.grid.tf/graphql

  grid-weblets:
    container_name: grid_weblets
    image: threefolddev/grid_weblets:v1.6.0-rc1
    restart: unless-stopped
    networks:
      tfgrid_bknd:
        ipv4_address: 172.28.0.9
    environment:
      - NETWORK=devnet
