networks:
  tfgrid_bknd:
    name: tfgrid_bknd
    ipam:
      driver: default

services:
## TFchain public node
  tfchain-public-node:
    container_name: tfchain-public-node
    volumes:
      - /srv/tfchain/:/storage/
    image: ghcr.io/threefoldtech/tfchain:${TFCHAIN_IMG}
    restart: unless-stopped
    networks:
      tfgrid_bknd:
    ports:
      - "127.0.0.1:9944:9944"
#      - "9933:9933"
      - "9615:9615"
      - "30333:30333"
    command:
      - "--node-key"
      - "${TFCHAIN_NODE_KEY}"
      - "--base-path"
      - "/storage"
      - "--chain"
      - "/etc/chainspecs/test/chainSpecRaw.json"
      - "--port"
      - "30333"
      - "--rpc-cors"
      - "all"
      - "--prometheus-external"
#      - "--ws-external"
      - "--rpc-max-connections=148576"
      - "--pruning"
      - "archive"
      - "--telemetry-url"
      - "wss://shard1.telemetry.tfchain.grid.tf/submit 1"
      - "--rpc-methods=Safe"
      - "--rpc-external"


## Caddy
  caddy:
    depends_on:
      tfchain-public-node:
        condition: service_started
    container_name: caddy
    image: caddy:${CADDY_IMG}
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      tfgrid_bknd:
    environment:
      DOMAIN: ${DOMAIN}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - /srv/caddy/data:/data
      - /srv/caddy/config:/config
      - /srv/caddy/log:/var/log/caddy
