version: "3.4"

services:
  grid-activation-service:
    image: tfchainactivationservice:1.0.1
    restart: unless-stopped
    environment:
      - URL=wss://tfchain.dev.grid.tf
      - MNEMONIC=news mad appear brave weekend first eyebrow blouse mask hedgehog toilet exhaust
      - KYC_PUBLIC_KEY=somekey
      - ACTIVATION_AMOUNT=1000000
