version: "3.7"

networks:
  tfgrid_bknd:
    name: tfgrid_bknd
    ipam:
      driver: default

services:
## TFchain public node
  tfchain-public-node:
    container_name: tfchain-public-node
    volumes:
      - /srv/tfchain/:/storage/
    image: ghcr.io/threefoldtech/tfchain:${TFCHAIN_IMG}
    restart: unless-stopped
    networks:
      tfgrid_bknd:
    ports:
#      - "127.0.0.1:9944:9944"
#      - "9933:9933"
#      - "9615:9615"
      - "30333:30333"
    command:
      - "--node-key"
      - "${TFCHAIN_NODE_KEY}"
      - "--base-path"
      - "/storage"
      - "--chain"
      - "/etc/chainspecs/test/chainSpecRaw.json"
      - "--port"
      - "30333"
      - "--bootnodes"
      - "/ip4/51.68.204.40/tcp/30333/ws/p2p/12D3KooWHe8Wbn6dDbyxXietaXSRTZJfykPRgrkJDjXh9xZ4383k"
      - "--rpc-cors"
      - "all"
      - "--prometheus-external"
#      - "--ws-external"
      - "--rpc-max-connections=148576"
      - "--pruning"
      - "archive"
      - "--telemetry-url"
      - "wss://shard1.telemetry.tfchain.grid.tf/submit 1"
      - "--rpc-methods=Safe"
      - "--rpc-external"


## Graphql - Indexer
  indexer_db:
    depends_on:
      tfchain-public-node:
        condition: service_started
    container_name: indexer_db
    image: cockroachdb/cockroach:${INDEXER_DB_IMG}
    restart: unless-stopped
    networks:
      tfgrid_bknd:
#    ports:
#      - "26257:26257"
#      - "8080:8080"
    command: start-single-node --insecure --cache=.5 --max-sql-memory=.5
    volumes:
      - /srv/indexer/:/cockroach/cockroach-data

  indexer_db-init:
    depends_on:
      - indexer_db
    container_name: indexer_db-init
    image: cockroachdb/cockroach:${INDEXER_DB_IMG}
    restart: on-failure
    networks:
      tfgrid_bknd:
    volumes:
      - ./setup_db.sh:/setup_db.sh
    entrypoint: "/bin/bash"
    command: /setup_db.sh

  indexer_ingest:
    depends_on:
      indexer_db-init:
        condition: service_completed_successfully
    container_name: indexer_ingest
    image: subsquid/substrate-ingest:${INDEXER_INGEST_IMG}
    restart: unless-stopped
    networks:
      tfgrid_bknd:
    volumes:
      - "./typesBundle.json:/configs/typesBundle.json"
    command:
      [
        "-e",
        "${WS_ENDPOINT}",
        "-c",
        "20",
        "--out",
        "postgres://root@indexer_db:26257/defaultdb",
        "--types-bundle",
        "/configs/typesBundle.json"
      ]

  indexer_gateway:
    depends_on:
      indexer_db-init:
        condition: service_completed_successfully
    image: subsquid/substrate-gateway:${INDEXER_GW_IMG}
    container_name: indexer_gateway
    restart: unless-stopped
    networks:
      tfgrid_bknd:
#    ports:
#      - "8888:8000"
    environment:
      DATABASE_MAX_CONNECTIONS: 5
      RUST_LOG: "actix_web=info,actix_server=info"
    command: [ "--database-url", "postgres://root@indexer_db:26257/defaultdb" ]

  indexer_explorer:
    depends_on:
      indexer_db-init:
        condition: service_completed_successfully
    container_name: indexer_explorer
    image: subsquid/substrate-explorer:${INDEXER_EXPL_IMG}
    restart: unless-stopped
    networks:
      tfgrid_bknd:
#    ports:
#      - "4444:3000"
    environment:
      DB_TYPE: cockroach
      DB_HOST: indexer_db
      DB_PORT: "26257"
      DB_NAME: "defaultdb"
      DB_USER: "root"


## Graphql - Processor
  processor_db:
    depends_on:
      indexer_explorer:
        condition: service_started
    container_name: processor_db
    image: postgres:${PROC_DB_IMG}
    restart: unless-stopped
    networks:
      tfgrid_bknd:
#    ports:
#      - "5432:5432"
    volumes:
      - /srv/processor/:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}

  processor:
    depends_on:
      processor_db:
        condition: service_started
    container_name: processor
    image: ghcr.io/threefoldtech/tfchain_graphql_processor:${PROC_IMG}
    restart: unless-stopped
    networks:
      tfgrid_bknd:
    ports:
      - 44233:44233
    env_file:
      - .env
    environment:
      - INDEXER_ENDPOINT_URL=${INDEXER_ENDPOINT_URL}
      - WS_URL=${WS_URL}
      - DB_HOST=processor_db
      - POLL_INTERVAL_MS=300
      - TYPEORM_LOGGING=error
#      - SQD_DEBUG=sqd:processor:*
    command: ["yarn", "process"]

  processor_query_node:
    depends_on:
      processor:
        condition: service_started
    container_name: processor_query_node
    image: ghcr.io/threefoldtech/tfchain_graphql_query-node:${PROC_QUERY_IMG}
    restart: unless-stopped
    networks:
      tfgrid_bknd:
#    ports:
#      - 4000:4000
    env_file:
      - .env
    environment:
      - DB_HOST=processor_db
